# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1flwq48RYzDzpkmYGScta9XOIUoywLtKb
"""

#Importar las librerias
import os
from typing import List
from random import choice
from google.colab import files

#Cargar documentos
doc = files.upload()

#Lectura del archivo
f = open ('lyrics.txt','r')
mensaje = f.read().upper()

def generateKey(string, key):
    key = list(key)
    if len(string) == len(key):
        return(key)
    else:
        for i in range(len(string) -
                       len(key)):
            key.append(key[i % len(key)])
    return("" . join(key))
     
def cipherText(string, key):
    cipher_text = []
    for i in range(len(string)):
        x = (ord(string[i]) +
             ord(key[i])) % 26
        x += ord('A')
        cipher_text.append(chr(x))
    return("" . join(cipher_text))
     
def originalText(cipher_text, key):
    orig_text = []
    for i in range(len(cipher_text)):
        x = (ord(cipher_text[i]) -
             ord(key[i]) + 26) % 26
        x += ord('A')
        orig_text.append(chr(x))
    return("" . join(orig_text))
     
if __name__ == "__main__":
    string = "Fuck"
    keyword = ["cielo","hile","hola","hilo"]
    keywordRandom = choice(keyword)
    keyRString = str(keywordRandom)
    print(mensaje)
    print("La key con la que se encrpta el texto es:"+keyRString)
    key = generateKey(mensaje, keyRString) 
    cipher_text = cipherText(mensaje,key)    
    print("Texto encriptado :", cipher_text)      
    for i in keyword:
      keyDesencriptar = generateKey(mensaje, i)      
      print("teto desencriptado "+str(i)+" :",originalText(cipher_text, keyDesencriptar))

#Creacion del archivo
doc = open("key.txt", "w")
#doc.write(keyRString+ os.linesep)
doc.close()

#Descarga del Archivo
files.download('key.txt')